public class JSON_EX_1 {
    /*public String integerValue {set;get;}
    public String decimalValue {set;get;}
    public String accountValue {set;get;}
    public String studentValue {set;get;}
    public String integerValuePreety {set;get;}
    public String decimalValuePreety {set;get;}
    public String accountValuePreety {set;get;}
    public String studentValuePreety {set;get;}
    public JSON_EX_1(){
        integerValue=JSON.serialize(10);
        decimalValue=JSON.serialize(14.65);
        Account acc=new Account(Name='TechUSA',Industry='Healthcare');
        accountValue=JSON.serialize(acc);
        Student stu=new Student('Rajesh','Mumbai','4325636');
        studentValue=JSON.serialize(stu);
        
        //Pretty
        integerValuePreety=JSON.serializepretty(10);
        decimalValuePreety=JSON.serializepretty(14.65);
        Account acc2=new Account(Name='TechUSA',Industry='Healthcare');
        Student stu2=new Student('Rajesh','Mumbai','4325636');
        accountValuePreety=JSON.serializepretty(acc2);
        studentValuePreety=JSON.serializepretty(stu2);
    }*/
    
    public String integerValue {set;get;}
    public String decimalValue {set;get;}
    public String accountValue {set;get;}
    public String studentValue {set;get;}
    public String integerValuePreety {set;get;}
    public String decimalValuePreety {set;get;}
    public String accountValuePreety {set;get;}
    public String studentValuePreety {set;get;}
    
    public JSON_EX_1(){
        
    }
}